import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "../components/CustomCursor";
import { SessionProvider } from "next-auth/react";


const  jetbrains= JetBrains_Mono({
  variable: "--font-jetbrains-semiBold",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrains.variable} antialiased`}
      ><SessionProvider>
        <CustomCursor />
        {children}
        </SessionProvider>
    
      </body>
    </html>
  );
}
